# 本番環境用
version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./docker/postgres/init.d:/docker-entrypoint-initdb.d
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: "Asia/Tokyo"
    hostname: ${DB_HOSTNAME}
    ports:
      - "${DB_PORT}:5432"
  app:
    build: 
      context: ./backend/
      dockerfile: Dockerfile.prod
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: app
    volumes:
      - ./backend:/backend
    environment:
      RAILS_ENV: development
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - db
  db-gui:
    container_name: db-gui
    image: dpage/pgadmin4
    volumes:
    # var/lib/pgadminのフォルダを作成しておく必要あり
      - ./docker/pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:80"